version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-toolkit
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongo-toolkit
    ports:
      - "27017:27017"